### ISSUE TITLE
SocksSharp Error

### ISSUE THREAD

**Issue by Wafend** [Laiteux/Milky#16]
Unhandled exception. System.MissingMethodException: Method not found: 'Void SocksSharp.ProxyClientHandler`1.set_AllowAutoRedirect(Boolean)'.
   at Milky.Models.Proxy.GetHttpMessageHandler()
   at Milky.Models.Proxy.GetHttpClient()
   at Milky.CheckerBuilder.WithProxies(IEnumerable`1 proxies)
   at Milky.CheckerBuilder.WithProxies(IEnumerable`1 proxies, ProxySettings settings)

I added this version of SocksSharp as a Reference "https://github.com/Laiteux/SocksSharp/releases/tag/1.1.0"
however i still get this message, when i checked the ProxyClientHandler class it indeed didnt have a set_AllowAutoRedirect Method
Did you maybe use a different version of SocksSharp?

**Comment by Laiteux** [comment]
Hey! https://github.com/Laiteux/SocksSharp

**Comment by Wafend** [comment]
Alright i built Milky with the source instead of with the releases and it worked
Thanks for your help and your amazing library <3
