### ISSUE TITLE
Feature request: Color as optional parameter on CheckResult (based on hit/free)

### ISSUE THREAD

**Issue by tcortega** [Laiteux/Milky#18]
Hello!
Title says it all, it's a feature request, its more like improving a current feature. Giving the option of choosing the color of the output in the console, based on Hit or Free. That way we don't have to mess with Milky's source (which I did to change), and we can change it using directly this function.

Might also be a good idea to add custom hit messages... But that's for the future 👍  

Thanks for making Milky, it's amazing and make my life so much easier!

**Comment by Laiteux** [comment]
Hey,

Nice suggestion, except it already exists 😁

Here is how you can do it:
```cs
new CheckerBuilder()
   .WithOutputSettings(new OutputSettings()
   {
      HitColor = ConsoleColor.Magenta,
      FreeColor = ConsoleColor.Yellow
   });
```

If everything is fine, please close this issue 🙂

**Comment by tcortega** [comment]
Didn't know about this, thanks for Milky again!
