### ISSUE TITLE
Clear cookies on first request

### ISSUE THREAD

**Issue by bartusbarilla001** [Laiteux/Milky#23]
Hello, I'm following the included example, however, I stumbled upon a weird issue, could be me for all I know, so I need to use cookies to keep the session up for capturing reasons, but whenever a next request "comes around", the session still seems to be alive and I have to kill it manually via calling a logout request or anything. 

Is there any way to solve that, like, clear cookies or whatever before the first request for a given combo?

**Comment by Laiteux** [comment]
![Telegram_EcVcPvie6g](https://user-images.githubusercontent.com/33204743/147304920-8a5d3289-52d0-4be0-aaaa-d12d46c5225e.jpg)
