### ISSUE TITLE
[suggestion] Disable redirects option

### ISSUE THREAD

**Issue by puff** [Laiteux/Milky#3]
Would you add an option to disable redirects? This could be done by ignoring the "Location" header from responses when you parse response headers.
Setting the MaximumAutomaticRedirects (Something like this, don't fully remember the name) integer to 0 will break the program.

**Comment by Laiteux** [comment]
Added, thanks for your suggestion.

```cs
request.AllowAutoRedirect = false;
```

Default is ``true``.
