### ISSUE TITLE
[suggestion] Default request headers

### ISSUE THREAD

**Issue by puff** [Laiteux/Milky#4]
Add default request headers. They would be automatically added to a MilkyRequest upon creation.
This would make the code cleaner and would also just be a little easier to code.

EX:

```cs
Milky.RequestUtils.AddDefaultHeader("User-Agent", "Mozilla 4.0");
using (MilkyRequest req = new MilkyRequest())
{
     MilkyResponse resp = Milky.RequestUtils.Execute(req, HttpMethod.GET, "https://google.com");
//Sends GET request to google.com with "Mozilla 4.0" User-Agent header
}
```

**Comment by Laiteux** [comment]
Milky isn't able to edit MilkyNet.

This is what you can do:
```cs
using MilkyNet;

namespace Issue_4
{
    class Program
    {
        static void Main(string[] args)
        {
            using(MilkyRequest request = DefaultRequest())
            {
                // Do whatever you want, request will have "Mozilla 4.0" User-Agent header
            }
        }

        static MilkyRequest DefaultRequest()
        {
            var request = new MilkyRequest();
            request.AddHeader("User-Agent", "Mozilla 4.0");

            return request;
        }
    }
}
```

**Comment by puff** [comment]
I forgot you could do that. Thanks 😆

**Comment by puff** [comment]
Reopening this because i just realized something

Looking at your code, I think it will remove the user-agent header if you try to make more than one request.
I meant the headers should retain after every request
Maybe something like this?
```
using (MilkyRequest req = new MilkyRequest())
{
     req.AddGlobalHeader("User-Agent", "123");
     MilkyResponse google = Milky.RequestUtils.Execute(req, HttpMethod.GET, "https://google.com/"); // GET https://google.com/ with "123" User-Agent header
     if (google.Status != HttpStatusCode.OK)
          Environment.Exit(-1);
     Milky.RequestUtils.Execute(req, HttpMethod.GET, "https://bing.com/"); // GET https://bing.com/ with "123" User-Agent header
}
```

**Comment by Laiteux** [comment]
Yes, headers are getting automatically cleared.
You can make a method which takes a MilkyRequest as parameter, add the headers you want to it then return it.

Or to keep the User-Agent header after request has been executed, do this:
```cs
var request = new MilkyRequest() { UserAgent = "Mozilla 4.0" };
```

**Comment by puff** [comment]
> Yes, headers are getting automatically cleared.
> You can make a method which takes a MilkyRequest as parameter, add the headers you want to it then return it.
> 
> Or to keep the User-Agent header after request has been executed, do this:
> 
> ```cs
> var request = new MilkyRequest() { UserAgent = "Mozilla 4.0" };
> ```

Alright, I believe I know how to do this now. Thanks :)
