### ISSUE TITLE
[suggestion] proxy authentication

### ISSUE THREAD

**Issue by puff** [Laiteux/Milky#6]
not sure if this is already implemented and i don't know how to use it, but it would be very useful for me

maybe add a custom format we can supply or something?
ex:

```
req.ProxyCredentials= "user:pass";
req.Proxy = "ip:port";

```

**Comment by Laiteux** [comment]
Sorry for the very late answer, I hope you figured out since.

```cs
var req = new xNet.HttpRequest();

req.Proxy = "ip:port";
req.Username = "user";
req.Password = "pass";
```
