### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by armangido** [Laiteux/Milky#9]
I got this error "System.IO.FileNotFoundException: 'Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.'"

This can be reproduce by importing Milky as reference.

**Comment by Laiteux** [comment]
Hello, can you please provide more details? What type of project are you trying to import Milky on?

**Comment by armangido** [comment]
Console type project

**Comment by Laiteux** [comment]
.NET Framework/Core?

**Comment by armangido** [comment]
.NET Framework 4.7.2

**Comment by Laiteux** [comment]
Try googling for the error, about to sleep sorry

**Comment by armangido** [comment]
tried searching  but can't really fix it..
can try to upload some test projects of yours  that linked with this?

**Comment by Laiteux** [comment]
Sure, feel free to upload stuff. I'll check tomorrow

**Comment by armangido** [comment]
No,  I mean can you upload some of  your projects ? that link with this Milky?

**Comment by Laiteux** [comment]
Oh alright, will do tmr.

**Comment by armangido** [comment]
Issue solved by changing target framework to .NET Core
